core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todoapp.urls")),
]

todoapp/api/urls.py
from rest_framework.authtoken.views import obtain_auth_token
from django.urls import path, include
from . import views

urlpatterns = [
    path("api-token-auth/", obtain_auth_token, name="api_token_auth"),
    path("todo/", views.TodoAPIView.as_view()),
    path("todo/<str:pk>", views.TodoAPIView.as_view()),
]

todoapp/urls.py
from django.urls import path, include

from . import views

app_name = "todoapp"
urlpatterns = [
    path("", views.TodoListView.as_view(), name="todo_list"),
    path("create-todo/", views.TodoCreateView.as_view(), name="create_todo"),
    path("update-todo/<int:pk>/", views.TodoUpdateView.as_view(), name="update_todo"),
    path("delete-todo/<int:pk>/", views.TodoDeleteView.as_view(), name="delete_todo"),
    path("todo/<int:pk>/", views.TodoDetailView.as_view(), name="todo_detail"),
    path("logout/", views.log_out, name="logout"),
    path("login/", views.log_in, name="login"),
    path("signup/", views.signup, name="signup"),
    path("api/", include("todoapp.api.urls")),
]

todoapp/models.py
from django.db import models
from django.utils.translation import gettext as _
from django.urls import reverse
from django.contrib.auth import get_user_model


UserModel = get_user_model()
# Create your models here.
class Todo(models.Model):
    CATEGORY_CHOICES = (
        ("normal", "Normal"),
        ("important", "Important"),
        ("urgent", "Urgent"),
    )
    title = models.CharField(_("Title"), max_length=50)
    description = models.TextField(_("Description"))
    category = models.CharField(
        _("category"), max_length=50, choices=CATEGORY_CHOICES, default="normal"
    )
    due_date = models.DateField(_("Due Date"))
    created_at = models.DateTimeField(_("Created At"), auto_now_add=True)
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("todoapp:todo_detail", args=[self.pk])

todoapp/forms.py
from django import forms
from . import models
from django.forms import widgets
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


UserModel = get_user_model()


class LogInForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(LogInForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"


class SignUpForm(UserCreationForm):
    class Meta:
        model = UserModel
        fields = ("username", "email")

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"


class TodoForm(forms.ModelForm):
    class Meta:
        model = models.Todo
        fields = "__all__"
        exclude = ["user"]
        widgets = {"due_date": widgets.DateInput(attrs={"type": "date"})}

    def __init__(self, *args, **kwargs):
        super(TodoForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"

todoapp/api/views.py
from rest_framework.response import Response
from todoapp.api.serializers import TodoSerializer
from todoapp.models import Todo
from rest_framework import status
from django.http.response import Http404
from rest_framework.views import APIView
from rest_framework.response import Response


class TodoAPIView(APIView):
    """
    A APIView to perform CRUD operation on todo table
    """

    def get_object(self, pk):
        try:
            todo = Todo.objects.get(pk=pk)
            if todo.user == self.request.user:
                return todo
            else:
                raise Http404
        except Todo.DoesNotExist:
            raise Http404

    def get(self, request, pk=None, format=None):
        if pk:
            data = self.get_object(pk)
            serializer = TodoSerializer(data)
        else:
            data = Todo.objects.filter(user=self.request.user).order_by("-created_at")
            serializer = TodoSerializer(data, many=True)

        return Response(serializer.data, status=status.HTTP_200_OK)

    def post(self, request, format=None):
        data = request.data
        serializer = TodoSerializer(data=data)

        serializer.is_valid(raise_exception=True)

        serializer.save(user=self.request.user)

        return Response(
            {
                "message": "Todo Created Successfully",
                "data": serializer.data,
            },
            status=status.HTTP_201_CREATED,
        )

    def put(self, request, pk=None, format=None):
        todo_to_update = self.get_object(pk)
        serializer = TodoSerializer(
            instance=todo_to_update, data=request.data, partial=True
        )

        serializer.is_valid(raise_exception=True)

        serializer.save()

        return Response(
            {
                "message": "Todo Updated Successfully",
                "data": serializer.data,
            },
            status=status.HTTP_200_OK,
        )

    def delete(self, request, pk, format=None):
        todo_to_delete = self.get_object(pk)

        todo_to_delete.delete()

        return Response(
            {"message": "Todo Deleted Successfully"}, status=status.HTTP_200_OK
        )

todoapp/views.py
from django.shortcuts import render, redirect
from django.views.generic import View, ListView, DetailView, DeleteView
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import login, authenticate, logout
from django.urls import reverse
from django.contrib import messages

from todoapp.forms import LogInForm, SignUpForm, TodoForm
from .models import Todo

# Create your views here.
class TodoListView(LoginRequiredMixin, ListView):
    """
    A ListView to display all todos
    """

    model = Todo
    context_object_name = "todo_list"
    template_name = "todo_list.html"

    def get_queryset(self):
        return self.model.objects.all().filter(user=self.request.user)


class TodoDetailView(LoginRequiredMixin, DetailView):
    """
    A DetailView to display todo detail
    """

    model = Todo
    template_name = "todo_detail.html"


class TodoCreateView(LoginRequiredMixin, CreateView):
    """
    A CreateView to create todo
    """

    model = Todo
    template_name = "todo_form.html"
    form_class = TodoForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(TodoCreateView, self).form_valid(form)


class TodoUpdateView(LoginRequiredMixin, UpdateView):
    """
    A UpdateView to update todo
    """

    model = Todo
    template_name = "todo_form.html"
    form_class = TodoForm

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


class TodoDeleteView(LoginRequiredMixin, DeleteView):
    """
    A DeleteView to delete todo
    """

    model = Todo
    template_name = "todo_confirm_delete.html"

    def get_success_url(self):
        return reverse("todoapp:todo_list")

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


def log_out(request):
    """
    Handle logout operation
    """
    logout(request)
    messages.success(request, "Logged out.")
    return redirect(reverse("todoapp:todo_list"))


def log_in(request):
    """
    Handle authenticate and login operation
    """
    if request.user.is_authenticated:
        return redirect("todoapp:todo_list")
    if request.method == "POST":
        form = LogInForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                messages.success(request, "Logged in.")
                return redirect("todoapp:todo_list")
    else:
        form = LogInForm()
    return render(request, "login.html", {"form": form})


def signup(request):
    """
    Handle signup operation
    """
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("todo_list")
    else:
        form = SignUpForm()
    return render(request, "signup.html", {"form": form})

todoapp/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock %}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
        <script src="https://use.fontawesome.com/8707e32926.js"></script>
        {% block css %}
        {% endblock %}
    </head>
    <body>
        <div class="container-fluid">
            <nav class="row" style="background: black; color: white;">
              <h1 class="col-md-12 text-center">TODO</h1>
            </nav>
            <div class="d-flex justify-content-end align-items-center pt-2">
              {% if user.is_authenticated %}
                <a href="#" class="nav-link mx-2">{{ user.get_username }}</a>
                <a href="{% url 'todoapp:logout' %}" class="btn btn-primary">Logout</a>
              {% else %}
                <a href="{% url 'todoapp:login' %}" class="btn btn-primary mx-3">Login</a>
                <a href="{% url 'todoapp:signup' %}" class="btn btn-primary">Singup</a>
              {% endif %}
            </div>
            {% if messages %}
              <div class="container pt-2">
                {% for message in messages %}
                  <div class="alert alert-success alert-dismissible fade show" role="alert">
                    {{ message  }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                  </div>
                {% endfor %}
              </div>
            {% endif %}
            {% block body %}
            {% endblock %}
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
        {% block js %}
        {% endblock %}
    </body>
</html>

todoapp/templates/login.html
{% extends 'base.html' %}
{% block body %}
<div class="container m-5 p-5 mt-0">
    {% if form.errors%}
    {% for field in form %}
    {% if field.errors %}
    <div class="alert alert-danger" role="alert">
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    {% endif %}

    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Submit" class="btn btn-primary mb-3">
    </form>
</div>
{% endblock%}

todoapp/templates/signup.html
{% extends 'base.html' %}
{% block body %}
<div class="container m-5 p-5 mt-0">
    {% if form.errors%}
    {% for field in form %}
    {% if field.errors %}
    <div class="alert alert-danger" role="alert">
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    {% endif %}

    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Submit" class="btn btn-primary mb-3">
    </form>
</div>
{% endblock%}

todoapp/templates/todo_confirm_delete.html
{% extends 'base.html' %}
{% block body %}
<div class="container m-5 p-5 mt-0">
    <form method="POST">
        <h3>Are you sure you want to delete task with title "{{ object.title }}"?</h3>
        {% csrf_token %}
        <input type="submit" value="Submit" class="btn btn-danger mt-3 mb-3">
        <a href="{% url 'todoapp:todo_list' %}" class="btn btn-secondary">Back</a>
    </form>
</div>
{% endblock%}

todoapp/templates/todo_detail.html
{% extends 'base.html' %}

{% block body %}
<div class="container m-5 p-5 pt-0">
    <div class="row">
        <div class="col-8">
            <h2 class="pb-4">Todo Detail</h2>    
        </div>
        <div class="col-4 d-flex justify-content-end align-items-center">
            <a class="btn btn-success" href="{% url 'todoapp:todo_list' %}" role="button"><i class="fa fa-list-ol" aria-hidden="true"></i> Todo List</a>
            <div class="p-3">
                {% comment %} <a class="btn btn-warning" href="{% url 'todoapp:update_user' object.id %}" role="button"><i class="fa fa-pencil" aria-hidden="true"></i> Update User</a> {% endcomment %}
            </div>
        </div>
    </div>
    <div class="container mt-4">
        <div class="row align-items-start mt-3">
            <div class="col-4">
                <b>Title</b>
            </div>
            <div class="col">
                {{object.title}}
            </div>
        </div>
        <div class="row align-items-start mt-3">
            <div class="col-4">
                <b>Category</b>
            </div>
            <div class="col">
                {{object.category}}
            </div>
        </div>
        <div class="row align-items-start mt-3">
            <div class="col-4">
                <b>Description</b>
            </div>
            <div class="col">
                {{object.description}}
            </div>
        </div>
        <div class="row align-items-start mt-3">
            <div class="col-4">
                <b>Due Date</b>
            </div>
            <div class="col">
                {{object.due_date}}
            </div>
        </div>
        <div class="row align-items-start mt-3">
            <div class="col-4">
                <b>Created At</b>
            </div>
            <div class="col">
                {{object.created_at}}
            </div>
        </div>
    </div>
</div>
{% endblock %}

todoapp/templates/todo_form.html
{% extends 'base.html' %}
{% block body %}
<div class="container m-5 p-5 mt-0">
    <div class="row">
        <div class="col-8">
            <h2 class="pb-4">{% if form.instance.pk %} Update Todo {% else %} Create Todo {% endif %}</h2>
        </div>
        <div class="col-4 d-flex justify-content-end align-items-center">
            <a class="btn btn-success" href="{% url 'todoapp:todo_list' %}" role="button"> <i class="fa fa-list-ol" aria-hidden="true"></i> Todo List</a>
        </div>
    </div>
    {% if form.errors%}
    {% for field in form %}
    {% if field.errors %}
    <div class="alert alert-danger" role="alert">
        {{ field.errors|striptags }}
    </div>
    {% endif %}
    {% endfor %}
    {% endif %}

    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Submit" class="btn btn-primary mb-3">
    </form>
</div>
{% endblock%}

todoapp/templates/todo_list.html
{% extends 'base.html' %}

{% block body %}
<div class="container m-5 p-5 pt-0">
    <div class="row">
        <div class="col-8">
            <h2>Todo List</h2>
        </div>
        <div class="col-4 d-flex justify-content-end align-items-center">
            <a class="btn btn-primary" href="{% url 'todoapp:create_todo' %}" role="button"><i class="fa fa-plus" aria-hidden="true"></i> New</a>
        </div>
    </div>
    <table class="table table-bordered table-dark mt-4">
        <thead>
          <tr>
            <th scope="col">No</th>
            <th scope="col">Title</th>
            <th scope="col">Category</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody>
        {% for todo in todo_list %}
            <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td>{{todo.title}}</td>
                <td>{{todo.category}}</td>
                <td>
                    <a class="btn btn-info" href='{% url "todoapp:todo_detail" todo.id %}'> <i class="fa fa-eye" aria-hidden="true"></i> View </a>
                    <a class="btn btn-warning" href="{% url 'todoapp:update_todo' todo.id %}" role="button"><i class="fa fa-pencil" aria-hidden="true"></i> Update</a>
                    <a class="btn btn-danger" href='{% url "todoapp:delete_todo" todo.id %}'> <i class="fa fa-trash" aria-hidden="true"></i> Delete </a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
      </table>
</div>
{% endblock %}